name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          key: test

      - name: Run tests
        run: cargo test -p remux-server
